[[plugins]]
  package = "netlify-plugin-cache-control"

  [plugins.inputs]
    headers = [
      "/*: Cache-Control: no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0",
      "/img/*: Cache-Control: no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0",
      "/css/*: Cache-Control: no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0",
      "/js/*: Cache-Control: no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0"
    ] 